version: '3'
services:
  web:
    build: .
    environment:
      - WEB_CONCURRENCY=4
    ports:
     - "80:80"
  dev:
    build: .
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
      - FLASK_ENV=development
      - WEB_CONCURRENCY=4
    volumes:
      - ./rmuse_app:/app
      - .:/repo
    ports:
      - "8080:8080"
